set -g mouse on
set -g history-limit 100000
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g automatic-rename on
set -g focus-events on
set -g default-terminal "tmux-256color"

# Avoid ESC delay
# Not 0 so we still parse ESCs
set -sg escape-time 10

set -g allow-predictions on

# Everforest dark medium color palette
%hidden EF_BG="#2D353B"
%hidden EF_FG="#D3C6AA"
%hidden EF_GREEN="#A7C080"
%hidden EF_AQUA="#83C092"
%hidden EF_BLUE="#7FBBB3"
%hidden EF_YELLOW="#DBBC7F"
%hidden EF_GREY0="#7A8478"
%hidden EF_GREY1="#343F44"

# Status bar theme
set -g status-style "bg=#2D353B,fg=#D3C6AA"
set -g status-left "#[bg=#{EF_AQUA},fg=#{EF_BG},bold] #S #[default]"
set -g window-status-style "fg=#7A8478"
set -g window-status-format " #I:#W#{?window_flags,#{window_flags}, } "
set -g window-status-current-style "bg=#7FBBB3,fg=#2D353B,bold"
set -g window-status-current-format " #I:#W#{?window_flags,#{window_flags}, } "
set -g window-status-separator ""
set -g message-style "bg=#2D353B,fg=#D3C6AA"
set -g pane-active-border-style "fg=#7FBBB3"
set -g pane-border-style "fg=#343F44"
# Show 'P' when prefix is active and 'C' when in copy mode, it doesn't go away unless there is a content after it or at the very least empty space after it
set -g status-right "#{?client_prefix,#[fg=#{EF_BG}]#[bold]#[bg=#{EF_BLUE}] P #[default],}#{?pane_in_mode,#[fg=#{EF_BG}]#[bold]#[bg=#{EF_YELLOW}] C #[default],} "

# Prefix + r to reload config
bind-key r source-file ~/.config/psmux/psmux.conf \; display-message 'Config reloaded!'

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
