set -g mouse on
set -g history-limit 100000
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g automatic-rename on
set -g focus-events on
set -g allow-predictions on

# Everforest dark medium status bar theme
set -g status-style "bg=#2D353B,fg=#D3C6AA"
set -g status-left "#[bg=#83C092,fg=#2D353B,bold] #S #[default] "
set -g window-status-format "#[fg=#7A8478] #I:#W "
set -g window-status-current-format "#[bg=#A7C080,fg=#2D353B,bold] #I:#W "
set -g window-status-separator ""
set -g message-style "bg=#DBBC7F,fg=#2D353B"
set -g pane-active-border-style "fg=#A7C080"
set -g pane-border-style "fg=#343F44"
# Show 'P' when prefix is active and 'C' when in copy mode, it doesn't go away unless there is a content after it or at the very least empty space after it
set -g status-right "#{?client_prefix,#[fg=#2D353B,bold]#[bg=#7FBBB3] P #[default],}#{?pane_in_mode,#[fg=#2D353B,bold]#[bg=#E69875] C #[default],} " 

# Prefix + R to reload config
bind-key R source-file ~/.config/psmux/psmux.conf \; display-message 'Config reloaded!'

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
