#!/usr/bin/env bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Load Screen Sharing
# @raycast.description Load the screen sharing service.
# @raycast.mode silent

# Documentation:
# @raycast.author Amr
# @raycast.authorURL https://amrbashir.me

launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist
