#!/usr/bin/env bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Unload Screen Sharing
# @raycast.description Unload the screen sharing service.
# @raycast.mode silent

# Documentation:
# @raycast.author Amr
# @raycast.authorURL https://amrbashir.me

launchctl unload -w /System/Library/LaunchDaemons/com.apple.screensharing.plist
