set -g mouse on
set -g history-limit 100000
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g automatic-rename on
set -g focus-events on
set -g default-terminal "tmux-256color"

# Avoid ESC delay
# Not 0 so we still parse ESCs
set -sg escape-time 10

# Everforest dark medium color palette
%hidden EF_BG="#2D353B"
%hidden EF_FG="#D3C6AA"
%hidden EF_GREEN="#A7C080"
%hidden EF_AQUA="#83C092"
%hidden EF_BLUE="#7FBBB3"
%hidden EF_ORANGE="#E69875"
%hidden EF_YELLOW="#DBBC7F"
%hidden EF_GREY0="#7A8478"
%hidden EF_GREY1="#343F44"

# Status bar theme
set -g status-style "bg=#{EF_BG},fg=#{EF_FG}"
set -g status-left "#[bg=#{EF_AQUA},fg=#{EF_BG},bold] #S #[default]"
set -g window-status-style "fg=#{EF_GREY0}"
set -g window-status-format " #I:#W#{?window_flags,#{window_flags}, } "
set -g window-status-current-style "bg=#{EF_GREEN},fg=#{EF_BG},bold"
set -g window-status-current-format " #I:#W#{?window_flags,#{window_flags}, } "
set -g window-status-separator ""
set -g message-style "bg=#{EF_YELLOW},fg=#{EF_BG}"
set -g pane-active-border-style "fg=#{EF_GREEN}"
set -g pane-border-style "fg=#{EF_GREY1}"
set -g status-right "#{?client_prefix,#[fg=#{EF_BG}]#[bold]#[bg=#{EF_BLUE}] P #[default],}#{?pane_in_mode,#[fg=#{EF_BG}]#[bold]#[bg=#{EF_YELLOW}] C #[default],}"

# Prefix + r to reload config
bind-key r source-file ~/.tmux.conf \; display-message 'Config reloaded!'

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
